version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  foodcritic:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
- "spec/"
- "test/"
