version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  paths:
  - "**.rb"
exclude_patterns:
- "spec/"
- "test/"
