version: "2"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
plugins:
  fixme:
    enabled: true
  foodcritic:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  paths:
  - "**.rb"
exclude_patterns:
- "spec/"
- "test/"
